node {
    // uncomment these 2 lines and edit the name 'node-4.6.0' according to what you choose in configuration
    // def nodeHome = tool name: 'node-4.6.0', type: 'jenkins.plugins.nodejs.tools.NodeJSInstallation'
    // env.PATH = "${nodeHome}/bin:${env.PATH}"

    stage('check tools') {
        sh "node -v"
        sh "npm -v"
        sh "bower -v"
        sh "gulp -v"
    }

    stage('checkout') {
        checkout scm
    }

    stage('npm install') {
        sh "npm install"
    }

    stage('clean') {
        sh "./mvnw clean"
    }

    stage('backend tests') {
        sh "./mvnw test"
    }

    stage('frontend tests') {
        sh "gulp test"
    }

    stage('packaging') {
        sh "./mvnw package -Pprod -DskipTests"
    }

    stage('Test') 
      parallel(demoapp: {
        dir('microservice-demo/demoapp') {
          docker.withRegistry('https://docker-registry-default.cloudapps.demo.tecdomain.net:5000'. 'microservice') {
            docker.withServer('tcp://127.0l0.1:4243') {
              docker.build('testi/demoapp').push('latest')
            }
          }
        }
      }
    
}
