node {
    // uncomment these 2 lines and edit the name 'node-4.6.0' according to what you choose in configuration
    // def nodeHome = tool name: 'node-4.6.0', type: 'jenkins.plugins.nodejs.tools.NodeJSInstallation'
    // env.PATH = "${nodeHome}/bin:${env.PATH}"

    stage('check tools') {
        sh "node -v"
        sh "npm -v"
        sh "bower -v"
        sh "gulp -v"
    }

    stage('checkout') {
        checkout scm
    }

    stage('npm install') {
        sh "npm install"
    }

    stage('clean') {
        dir('microservice-demo/demoapp') {
          sh "./mvnw clean"
        }
    }

    stage('backend tests') {
        dir('microservice-demo/demoapp') {
          sh "./mvnw test"
        }
    }

    stage('frontend tests') {
        dir('microservice-demo/demoapp') {
          sh "gulp test"
        }
    }

    stage('packaging') {
        dir('microservice-demo/demoapp') {
          sh "./mvnw package -Pprod -DskipTests"
        }
    }

    stage('Test') {
      parallel(demoapp: {
        dir('microservice-demo/demoapp') {
          docker.withRegistry('https://docker-registry-default.cloudapps.demo.tecdomain.net', 'openshift') {
            docker.withServer('tcp://127.0.0.1:4243') {
              docker.build('microservice/demoapp').push('latest')
            }
          }
        }
      })
   }
}
